%Read in Consp Cons data

clear;
clc;

cd '/gpfs/home/dcj138/work/CEX_code/'

consdat = dlmread('merged_cex.csv',',',1,0);

mainspread = dlmread('MainSpread.csv',',',1,2);

%Categorizing all the things:

%cons: each row is an observation, and expenditures in the 29 categories 
%cons order: FdH, FdO, Cig, AlH, AlO, Clo, Lry, Jwl, Brb, Hom, Htl, Fur,
%Utl, Tel, HIn, Med, Fee, LIn, Car, CMn, Gas, CIn, Bus, Air, Bks, Ot1, Ot2,
%Edu, Cha

ind = 33;
cons = [consdat(:,ind+2),...
    consdat(:,ind+1)+consdat(:,ind+3),...
    consdat(:,ind+4),...
    consdat(:,ind+6),...
    consdat(:,ind+5),...
    consdat(:,ind+7),...
    consdat(:,ind+8),...
    consdat(:,ind+9),...
    consdat(:,ind+11),...
    consdat(:,ind+12),...
    consdat(:,ind+13),...
    consdat(:,ind+14)+consdat(:,ind+15),...
    consdat(:,ind+16)+consdat(:,ind+17)+consdat(:,ind+18)+consdat(:,ind+19),...
    consdat(:,ind+20),...
    consdat(:,ind+21),...
    consdat(:,ind+22)+consdat(:,ind+23)+consdat(:,ind+24)+consdat(:,ind+25)+consdat(:,ind+26)+consdat(:,ind+27),...
    consdat(:,ind+28),...
    consdat(:,ind+29),...
    consdat(:,ind+30),...
    consdat(:,ind+31)+consdat(:,ind+32),...
    consdat(:,ind+33),...
    consdat(:,ind+35),...
    consdat(:,ind+36)+consdat(:,ind+37),...
    consdat(:,ind+38),...
    consdat(:,ind+39)+consdat(:,ind+40),...
    consdat(:,ind+41),...
    consdat(:,ind+42),...
    consdat(:,ind+44)+consdat(:,ind+45)+consdat(:,ind+46),...
    consdat(:,ind+47)];

%price: same order as cons
price = [mainspread(1:6,5:end-2);mainspread(8:15,5:end-2);mainspread(17:end,5:end-2)]';

%visibility indexes: column ordr the same, row order: Not black under 40, Not black over 40, Black under 40, Black over 40;
vin = [mainspread(1:6,1:4);mainspread(8:15,1:4);mainspread(17:end,1:4)]';
 
clearvars -except cons price vin

save '/gpfs/home/dcj138/work/ConspCons/dat' 